// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WM.Modules.TimeAttendance.Data;

#nullable disable

namespace WM.Modules.TimeAttendance.Data.Migrations
{
    [DbContext(typeof(TimeAttendanceDbContext))]
    [Migration("20260924194646_PunchReceivedAt")]
    partial class PunchReceivedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("time_attendance")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WM.Modules.TimeAttendance.Domain.DayTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("AllocateToPreviousDayWindow")
                        .HasColumnType("interval");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<TimeOnly?>("NightShiftEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("OffsetAfterTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("OffsetTransactionToNextDay")
                        .HasColumnType("boolean");

                    b.Property<bool>("OverriddenByMasterTemplate")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DayTemplates", "time_attendance");
                });

            modelBuilder.Entity("WM.Modules.TimeAttendance.Domain.MasterTemplateAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("MasterTemplateId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("MasterTemplateId");

                    b.ToTable("MasterTemplateAssignments", "time_attendance", t =>
                        {
                            t.HasCheckConstraint("ck_master_template_assignments_window", "\"StartDate\" IS NULL OR \"EndDate\" IS NULL OR \"StartDate\" <= \"EndDate\"");
                        });
                });

            modelBuilder.Entity("WM.Modules.TimeAttendance.Domain.Punch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ClientUtcOffsetMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Flags")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<DateOnly?>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("LocalZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("EmployeeId", "LocalDate");

                    b.HasIndex("EmployeeId", "Timestamp");

                    b.ToTable("Punches", "time_attendance");
                });

            modelBuilder.Entity("WM.Modules.TimeAttendance.Domain.ShiftMatchingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DayTemplateId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("EndTimeFrom")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("EndTimeTo")
                        .HasColumnType("time without time zone");

                    b.Property<int>("MatchType")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("StartTimeFrom")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("StartTimeTo")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("TemplateToAssignId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DayTemplateId");

                    b.HasIndex("TemplateToAssignId");

                    b.ToTable("ShiftMatchingRules", "time_attendance");
                });

            modelBuilder.Entity("WM.Modules.TimeAttendance.Domain.MasterTemplateAssignment", b =>
                {
                    b.HasOne("WM.Modules.TimeAttendance.Domain.DayTemplate", null)
                        .WithMany()
                        .HasForeignKey("MasterTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WM.Modules.TimeAttendance.Domain.ShiftMatchingRule", b =>
                {
                    b.HasOne("WM.Modules.TimeAttendance.Domain.DayTemplate", null)
                        .WithMany("ShiftMatchingRules")
                        .HasForeignKey("DayTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WM.Modules.TimeAttendance.Domain.DayTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateToAssignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WM.Modules.TimeAttendance.Domain.DayTemplate", b =>
                {
                    b.Navigation("ShiftMatchingRules");
                });
#pragma warning restore 612, 618
        }
    }
}
