<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\WM.SharedKernel\WM.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Modules\Identity\WM.Modules.Identity\WM.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\People\WM.Modules.People\WM.Modules.People.csproj" />
    <ProjectReference Include="..\..\Modules\TimeAttendance\WM.Modules.TimeAttendance\WM.Modules.TimeAttendance.csproj" />
    <ProjectReference Include="..\..\Licensing\WM.Licensing\WM.Licensing.csproj" />
  </ItemGroup>
</Project>
